# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test3(self):
    self.driver.get("http://127.0.0.1:56199/")
    self.driver.set_window_size(1722, 1034)
    self.driver.find_element(By.CSS_SELECTOR, ".arrow").click()
    self.driver.find_element(By.CSS_SELECTOR, ".currency-icon").click()
    self.driver.find_element(By.NAME, "currency_code").click()
    dropdown = self.driver.find_element(By.NAME, "currency_code")
    dropdown.find_element(By.XPATH, "//option[. = 'JPY']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(7) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary").click()
    self.driver.find_element(By.ID, "country").click()
    self.driver.find_element(By.ID, "zip_code").click()
    self.driver.find_element(By.ID, "zip_code").send_keys("12345")
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-5 > .cymbal-dropdown-chevron").click()
    self.driver.find_element(By.ID, "credit_card_expiration_month").click()
    dropdown = self.driver.find_element(By.ID, "credit_card_expiration_month")
    dropdown.find_element(By.XPATH, "//option[. = 'May']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Continue Shopping").click()
  
